version: '3.8'

volumes:
    logs:
        driver: local
    my-db:
    my-files:
    mysql-data:
services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - 9191:80
        environment:
            MYSQL_USERNAME: user
            MYSQL_ROOT_PASSWORD: secret
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'secret'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'secret'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql
            - my-files:/var/lib/mysql-files
    app:
        container_name: date-app
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
            - mysql-data:/var/lib/mysql-files
